version: '2'
services:
  earthquake-backend:
    container_name: earthquake-backend
    build:
      dockerfile: Dockerfile
    image: earthquake-backend:latest
    ports:
      - 8080:8080
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge